import type { Metadata } from "next";
import localFont from "next/font/local";
import { Lora } from 'next/font/google'
import "./globals.css";
import 'aos/dist/aos.css'; 
import Menu from "./Navigator/menu";

const lora = Lora({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
 
  
  return (
    <html lang="en">
      <body className={lora.className}>
        <Menu/>
        {children}
      </body>
    </html>
  );
}
